import type { Role } from '@/lib/types/role'

export interface NavItem {
  label: string
  icon: string
  path: string
  section: string
  roles: Role[]
}

export interface NavSection {
  label: string
  items: NavItem[]
}

export const navigationRegistry: NavItem[] = [
  // ─── STUDENT ────────────────────────────────────
  {
    label: 'Dashboard',
    icon: 'LayoutDashboard',
    path: '/student/dashboard',
    section: 'Dashboard',
    roles: ['STUDENT'],
  },
  {
    label: 'Catalogue Search',
    icon: 'Search',
    path: '/student/catalogue',
    section: 'Discover & Learn',
    roles: ['STUDENT'],
  },
  {
    label: 'Courses & Materials',
    icon: 'GraduationCap',
    path: '/student/courses',
    section: 'Discover & Learn',
    roles: ['STUDENT'],
  },
  {
    label: 'E-Resources',
    icon: 'Globe',
    path: '/student/eresources',
    section: 'Discover & Learn',
    roles: ['STUDENT'],
  },
  {
    label: 'Newspapers',
    icon: 'Newspaper',
    path: '/student/newspapers',
    section: 'Discover & Learn',
    roles: ['STUDENT'],
  },
  {
    label: 'Bookmarks',
    icon: 'Bookmark',
    path: '/student/bookmarks',
    section: 'My Library',
    roles: ['STUDENT'],
  },
  {
    label: 'Holds & Returns',
    icon: 'PackageCheck',
    path: '/student/holds',
    section: 'My Library',
    roles: ['STUDENT'],
  },
  {
    label: 'History',
    icon: 'ScrollText',
    path: '/student/history',
    section: 'My Library',
    roles: ['STUDENT'],
  },
  {
    label: 'Fines & Charges',
    icon: 'CircleDollarSign',
    path: '/student/fines',
    section: 'My Library',
    roles: ['STUDENT'],
  },
  {
    label: 'Events',
    icon: 'CalendarCheck',
    path: '/student/events',
    section: 'Notices',
    roles: ['STUDENT'],
  },
  {
    label: 'Announcements',
    icon: 'Megaphone',
    path: '/student/announcements',
    section: 'Notices',
    roles: ['STUDENT'],
  },
  {
    label: 'Policies',
    icon: 'ShieldCheck',
    path: '/student/policies',
    section: 'Notices',
    roles: ['STUDENT'],
  },
  {
    label: 'Role Requests',
    icon: 'Shield',
    path: '/student/requests',
    section: 'Requests & Inquiries',
    roles: ['STUDENT'],
  },
  {
    label: 'Feedback & Inquiries',
    icon: 'MessageSquare',
    path: '/student/feedback',
    section: 'Requests & Inquiries',
    roles: ['STUDENT'],
  },
  {
    label: 'Help Centre',
    icon: 'HelpCircle',
    path: '/student/help',
    section: 'Support',
    roles: ['STUDENT'],
  },
  {
    label: 'Feedback',
    icon: 'Star',
    path: '/student/general-feedback',
    section: 'Support',
    roles: ['STUDENT'],
  },
  {
    label: 'Profile',
    icon: 'User',
    path: '/student/profile',
    section: 'Account',
    roles: ['STUDENT'],
  },
  {
    label: 'Settings',
    icon: 'Settings',
    path: '/student/settings',
    section: 'Account',
    roles: ['STUDENT'],
  },

  // ─── STAFF ──────────────────────────────────────
  {
    label: 'Dashboard',
    icon: 'LayoutDashboard',
    path: '/staff/dashboard',
    section: 'Dashboard',
    roles: ['STAFF'],
  },
  {
    label: 'Catalogue Search',
    icon: 'Search',
    path: '/staff/catalogue',
    section: 'Discover & Learn',
    roles: ['STAFF'],
  },
  {
    label: 'Courses & Materials',
    icon: 'GraduationCap',
    path: '/staff/courses',
    section: 'Discover & Learn',
    roles: ['STAFF'],
  },
  {
    label: 'E-Resources',
    icon: 'Globe',
    path: '/staff/eresources',
    section: 'Discover & Learn',
    roles: ['STAFF'],
  },
  {
    label: 'Newspapers',
    icon: 'Newspaper',
    path: '/staff/newspapers',
    section: 'Discover & Learn',
    roles: ['STAFF'],
  },
  {
    label: 'Bookmarks',
    icon: 'Bookmark',
    path: '/staff/bookmarks',
    section: 'My Library',
    roles: ['STAFF'],
  },
  {
    label: 'Holds & Returns',
    icon: 'PackageCheck',
    path: '/staff/holds',
    section: 'My Library',
    roles: ['STAFF'],
  },
  {
    label: 'History',
    icon: 'ScrollText',
    path: '/staff/history',
    section: 'My Library',
    roles: ['STAFF'],
  },
  {
    label: 'Fines & Charges',
    icon: 'CircleDollarSign',
    path: '/staff/fines',
    section: 'My Library',
    roles: ['STAFF'],
  },
  {
    label: 'Events',
    icon: 'CalendarCheck',
    path: '/staff/events',
    section: 'Notices',
    roles: ['STAFF'],
  },
  {
    label: 'Announcements',
    icon: 'Megaphone',
    path: '/staff/announcements',
    section: 'Notices',
    roles: ['STAFF'],
  },
  {
    label: 'Policies',
    icon: 'ShieldCheck',
    path: '/staff/policies',
    section: 'Notices',
    roles: ['STAFF'],
  },
  {
    label: 'AV & Boardroom',
    icon: 'Video',
    path: '/staff/booking',
    section: 'Spaces & Bookings',
    roles: ['STAFF'],
  },
  {
    label: 'Equipment Booking',
    icon: 'Monitor',
    path: '/staff/equipment-booking',
    section: 'Spaces & Bookings',
    roles: ['STAFF'],
  },
  {
    label: 'Role / Access Requests',
    icon: 'Shield',
    path: '/staff/requests',
    section: 'Requests',
    roles: ['STAFF'],
  },
  {
    label: 'Feedback & Inquiries',
    icon: 'MessageSquare',
    path: '/staff/feedback',
    section: 'Requests',
    roles: ['STAFF'],
  },
  {
    label: 'Help Centre',
    icon: 'HelpCircle',
    path: '/staff/help',
    section: 'Support',
    roles: ['STAFF'],
  },
  {
    label: 'Profile',
    icon: 'User',
    path: '/staff/profile',
    section: 'Account',
    roles: ['STAFF'],
  },
  {
    label: 'Settings',
    icon: 'Settings',
    path: '/staff/settings',
    section: 'Account',
    roles: ['STAFF'],
  },

  // ─── DESK ───────────────────────────────────────
  {
    label: 'Dashboard',
    icon: 'LayoutDashboard',
    path: '/desk/dashboard',
    section: 'Dashboard',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Issue & Returns',
    icon: 'ArrowDownToLine',
    path: '/desk/returns',
    section: 'Circulation Desk',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Issue Log',
    icon: 'ScrollText',
    path: '/desk/issue-log',
    section: 'Circulation Desk',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Lost & Found',
    icon: 'SearchCheck',
    path: '/desk/lost-found',
    section: 'Circulation Desk',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Daily Report',
    icon: 'BarChart2',
    path: '/desk/reports',
    section: 'Circulation Desk',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Overdues Report',
    icon: 'AlertTriangle',
    path: '/desk/overdues-report',
    section: 'Circulation Desk',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Inventory',
    icon: 'Package',
    path: '/desk/inventory',
    section: 'Management',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Book Management',
    icon: 'BookOpen',
    path: '/desk/items',
    section: 'Management',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Member Management',
    icon: 'Users',
    path: '/desk/members',
    section: 'Management',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Access Cards',
    icon: 'CreditCard',
    path: '/desk/cards',
    section: 'Management',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Catalogue Search',
    icon: 'Search',
    path: '/desk/catalogue',
    section: 'Discover & Learn',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Courses & Materials',
    icon: 'GraduationCap',
    path: '/desk/courses',
    section: 'Discover & Learn',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'E-Resources',
    icon: 'Globe',
    path: '/desk/eresources',
    section: 'Discover & Learn',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Newspapers',
    icon: 'Newspaper',
    path: '/desk/newspapers',
    section: 'Discover & Learn',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Bookmarks',
    icon: 'Bookmark',
    path: '/desk/bookmarks',
    section: 'My Library',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Holds & Returns',
    icon: 'PackageCheck',
    path: '/desk/holds',
    section: 'My Library',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'History',
    icon: 'Clock',
    path: '/desk/history',
    section: 'My Library',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Fines & Charges',
    icon: 'CircleDollarSign',
    path: '/desk/fines',
    section: 'My Library',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Events',
    icon: 'CalendarCheck',
    path: '/desk/events',
    section: 'Notices',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Announcements',
    icon: 'Megaphone',
    path: '/desk/announcements',
    section: 'Notices',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Policies',
    icon: 'ShieldCheck',
    path: '/desk/policies',
    section: 'Notices',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Help Centre',
    icon: 'HelpCircle',
    path: '/desk/help',
    section: 'Support',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Feedback & Inquiries',
    icon: 'MessageSquare',
    path: '/desk/feedback',
    section: 'Support',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Profile',
    icon: 'User',
    path: '/desk/profile',
    section: 'Account',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },
  {
    label: 'Settings',
    icon: 'Settings',
    path: '/desk/settings',
    section: 'Account',
    roles: ['ASSISTANT', 'CAPTAIN', 'PREFECT'],
  },

  // ─── LIBRARY HEAD ───────────────────────────────
  {
    label: 'Dashboard',
    icon: 'LayoutDashboard',
    path: '/library-head/dashboard',
    section: 'Dashboard',
    roles: ['LIBRARY_HEAD'],
  },
  {
    label: 'Operations',
    icon: 'Activity',
    path: '/library-head/operations',
    section: 'Management',
    roles: ['LIBRARY_HEAD'],
  },
  {
    label: 'Inventory & Stocktake',
    icon: 'Package',
    path: '/library-head/inventory',
    section: 'Management',
    roles: ['LIBRARY_HEAD'],
  },
  {
    label: 'Member Management',
    icon: 'Users',
    path: '/library-head/members',
    section: 'Management',
    roles: ['LIBRARY_HEAD'],
  },
  {
    label: 'Staff',
    icon: 'BriefcaseBusiness',
    path: '/library-head/staff',
    section: 'Management',
    roles: ['LIBRARY_HEAD'],
  },
  {
    label: 'Access Cards',
    icon: 'CreditCard',
    path: '/library-head/access-cards',
    section: 'Management',
    roles: ['LIBRARY_HEAD'],
  },
  {
    label: 'Approval Queues',
    icon: 'ClipboardCheck',
    path: '/library-head/requests',
    section: 'Management',
    roles: ['LIBRARY_HEAD'],
  },
  {
    label: 'Lost & Found',
    icon: 'SearchCheck',
    path: '/library-head/lost-found',
    section: 'Management',
    roles: ['LIBRARY_HEAD'],
  },
  {
    label: 'Charges & Loans',
    icon: 'BarChart2',
    path: '/library-head/charges',
    section: 'Management',
    roles: ['LIBRARY_HEAD'],
  },
  {
    label: 'Material',
    icon: 'BookPlus',
    path: '/library-head/catalogue',
    section: 'Content',
    roles: ['LIBRARY_HEAD'],
  },
  {
    label: 'Events',
    icon: 'CalendarCheck',
    path: '/library-head/events',
    section: 'Notices',
    roles: ['LIBRARY_HEAD'],
  },
  {
    label: 'Announcements',
    icon: 'Megaphone',
    path: '/library-head/announcements',
    section: 'Notices',
    roles: ['LIBRARY_HEAD'],
  },
  {
    label: 'Policies',
    icon: 'ShieldCheck',
    path: '/library-head/policies',
    section: 'Notices',
    roles: ['LIBRARY_HEAD'],
  },
  {
    label: 'Courses',
    icon: 'GraduationCap',
    path: '/library-head/courses',
    section: 'Courses',
    roles: ['LIBRARY_HEAD'],
  },
  {
    label: 'E-Resources',
    icon: 'Globe',
    path: '/library-head/eresources',
    section: 'E-Resources & Stock',
    roles: ['LIBRARY_HEAD'],
  },
  {
    label: 'Equipment',
    icon: 'Monitor',
    path: '/library-head/equipment',
    section: 'E-Resources & Stock',
    roles: ['LIBRARY_HEAD'],
  },
  {
    label: 'Help Centre',
    icon: 'HelpCircle',
    path: '/library-head/help',
    section: 'Support',
    roles: ['LIBRARY_HEAD'],
  },
  {
    label: 'Feedback & Inquiries',
    icon: 'MessageSquare',
    path: '/library-head/feedback',
    section: 'Support',
    roles: ['LIBRARY_HEAD'],
  },
  {
    label: 'Messages',
    icon: 'MessageCircle',
    path: '/library-head/messages',
    section: 'Support',
    roles: ['LIBRARY_HEAD'],
  },
  {
    label: 'Profile',
    icon: 'User',
    path: '/library-head/profile',
    section: 'Account',
    roles: ['LIBRARY_HEAD'],
  },
  {
    label: 'Settings',
    icon: 'Settings',
    path: '/library-head/settings',
    section: 'Account',
    roles: ['LIBRARY_HEAD'],
  },

  // ─── EXECUTIVE ──────────────────────────────────
  {
    label: 'Dashboard',
    icon: 'LayoutDashboard',
    path: '/executive/dashboard',
    section: 'Dashboard',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'Reports & Analytics',
    icon: 'BarChart2',
    path: '/executive/reports',
    section: 'Governance',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'Policy Rules',
    icon: 'ShieldCheck',
    path: '/executive/policies',
    section: 'Governance',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'Approval Queue',
    icon: 'ClipboardCheck',
    path: '/executive/approvals',
    section: 'Governance',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'Roles Overview',
    icon: 'Users',
    path: '/executive/roles',
    section: 'Governance',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'Account Lookup',
    icon: 'UserSearch',
    path: '/executive/accounts',
    section: 'Governance',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'Catalogue Search',
    icon: 'Search',
    path: '/executive/catalogue',
    section: 'Discover & Learn',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'E-Resources',
    icon: 'Globe',
    path: '/executive/eresources',
    section: 'Discover & Learn',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'Newspapers',
    icon: 'Newspaper',
    path: '/executive/newspapers',
    section: 'Discover & Learn',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'Bookmarks',
    icon: 'Bookmark',
    path: '/executive/bookmarks',
    section: 'My Library',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'Holds & Returns',
    icon: 'PackageCheck',
    path: '/executive/holds',
    section: 'My Library',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'History',
    icon: 'ScrollText',
    path: '/executive/history',
    section: 'My Library',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'Fines & Charges',
    icon: 'CircleDollarSign',
    path: '/executive/fines',
    section: 'My Library',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'AV & Boardroom',
    icon: 'Video',
    path: '/executive/av-rooms',
    section: 'Spaces & Bookings',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'Physical Books',
    icon: 'BookOpen',
    path: '/executive/books',
    section: 'Spaces & Bookings',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'Events',
    icon: 'CalendarCheck',
    path: '/executive/events',
    section: 'Notices',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'Announcements',
    icon: 'Megaphone',
    path: '/executive/announcements',
    section: 'Notices',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'Policies',
    icon: 'FileText',
    path: '/executive/policies-list',
    section: 'Notices',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'Help Centre',
    icon: 'HelpCircle',
    path: '/executive/help',
    section: 'Support',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'Feedback & Inquiries',
    icon: 'MessageSquare',
    path: '/executive/feedback',
    section: 'Support',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'Profile',
    icon: 'User',
    path: '/executive/profile',
    section: 'Account',
    roles: ['EXECUTIVE'],
  },
  {
    label: 'Settings',
    icon: 'Settings',
    path: '/executive/settings',
    section: 'Account',
    roles: ['EXECUTIVE'],
  },

  // ─── SUPER ADMIN ────────────────────────────────
  {
    label: 'Dashboard',
    icon: 'LayoutDashboard',
    path: '/super-admin/dashboard',
    section: 'System Overview',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'Users & Roles',
    icon: 'Users',
    path: '/super-admin/users',
    section: 'Core Management',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'All Access Dashboard',
    icon: 'Grid3X3',
    path: '/super-admin/dashboards',
    section: 'Core Management',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'Members',
    icon: 'UserCheck',
    path: '/super-admin/members',
    section: 'Core Management',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'QR Cards',
    icon: 'CreditCard',
    path: '/super-admin/qr-cards',
    section: 'Core Management',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'Permissions',
    icon: 'KeyRound',
    path: '/super-admin/permissions',
    section: 'Core Management',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'System Announcements',
    icon: 'Megaphone',
    path: '/super-admin/system-announcements',
    section: 'Core Management',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'Catalog Management',
    icon: 'BookPlus',
    path: '/super-admin/catalogue',
    section: 'Library Management',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'Inventory & Stock',
    icon: 'Package',
    path: '/super-admin/inventory',
    section: 'Library Management',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'Loans & Transactions',
    icon: 'ScrollText',
    path: '/super-admin/loans',
    section: 'Library Management',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'Reservations & Bookings',
    icon: 'CalendarCheck',
    path: '/super-admin/bookings',
    section: 'Library Management',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'Learning Resources',
    icon: 'GraduationCap',
    path: '/super-admin/learning-resources',
    section: 'Library Management',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'Settings & Preferences',
    icon: 'Settings',
    path: '/super-admin/config',
    section: 'System Configuration',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'Automations & Jobs',
    icon: 'Cog',
    path: '/super-admin/automations',
    section: 'System Configuration',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'Policies & Rules',
    icon: 'ShieldCheck',
    path: '/super-admin/policies',
    section: 'System Configuration',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'Feature Flags',
    icon: 'ToggleRight',
    path: '/super-admin/feature-flags',
    section: 'System Configuration',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'Integrations',
    icon: 'Plug',
    path: '/super-admin/integrations',
    section: 'System Configuration',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'Databases & Backups',
    icon: 'Database',
    path: '/super-admin/backups',
    section: 'Maintenance',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'Logs & Monitoring',
    icon: 'Terminal',
    path: '/super-admin/logs',
    section: 'Maintenance',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'System Health',
    icon: 'Activity',
    path: '/super-admin/health',
    section: 'Maintenance',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'Audit Trails',
    icon: 'FileCheck',
    path: '/super-admin/audit-trails',
    section: 'Maintenance',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'Profile',
    icon: 'User',
    path: '/super-admin/profile',
    section: 'Account',
    roles: ['SUPER_ADMIN'],
  },
  {
    label: 'Settings',
    icon: 'Settings',
    path: '/super-admin/settings',
    section: 'Account',
    roles: ['SUPER_ADMIN'],
  },
]

export function getNavigationForRole(role: Role): NavItem[] {
  return navigationRegistry.filter((item) => item.roles.includes(role))
}

export function getNavigationSections(role: Role): NavSection[] {
  const items = getNavigationForRole(role)
  return groupNavigationBySection(items)
}

export function groupNavigationBySection(items: NavItem[]): NavSection[] {
  const sectionMap = new Map<string, NavItem[]>()
  for (const item of items) {
    const existing = sectionMap.get(item.section) ?? []
    existing.push(item)
    sectionMap.set(item.section, existing)
  }
  return Array.from(sectionMap.entries()).map(([label, sectionItems]) => ({
    label,
    items: sectionItems,
  }))
}
